name:                wavemaker
version:             0.1.0.0
github:              "beaszt-nix/wavemaker"
license:             BSD3
author:              "Anjan Srihari"
maintainer:          "anjansrihari14@gmail.com"
copyright:           "2021 Anjan Srihari" 
extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wavemaker#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- array
- vector
- transformers
- bytestring
- parsec
- binary

library:
  source-dirs: src

executables:
  wavemaker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wavemaker

tests:
  wavemaker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wavemaker
